FROM flowiseai/flowise:3.1.1
 
USER root
 
# Community-Node-Ordner anlegen und Paket + fehlende Abhängigkeit fest installieren
# RUN mkdir -p /home/node/.n8n/nodes \
#     && cd /home/node/.n8n/nodes \
#     && npm init -y \
#     && npm install n8n-nodes-nostrobots@1.2.1 @noble/hashes@1.3.1 \
#     && chown -R node:node /home/node/.n8n
 
USER node
 
